### ISSUE TITLE
might be useful to include a nodemon reminder

### ISSUE THREAD

**Issue by starsuit** [foundersandcoders/ws-pure-functions-easy-testing#7]
We learned nodemon yesterday but as it was a code-along it's not in the wk2 docs anywhere. Possibly a reminder in this exercise would be useful.

**Comment by zurda** [comment]
Thanks for the suggestion @starsuit ! 
I agree- this would be a valuable optional step in setting up the project. With FAC-16 we ended up stopping the workshop for a few minutes to walk everyone through adding nodemon to their project, so having it in the README might save time and prevent confusion.

**Comment by oliverjam** [comment]
Merged
